type Query {
    getAllPerson: [Person]
    getPersonById(personId: String!): Person
    searchPersonQuery(name: String!): [Person]
    vitalsByPersonId(personId: ID!): [Vital]
}

type Person {
    personId: ID
    name: String
    address: String
    dateOfBirth: String
    gender: String
    nationality: String
    religion: String
}

type Vital {
    vitalId: ID
    temperature: Float
    bloodPressure: String
    pulseRate: Int
    respiratoryRate: Int
    oxygenSaturation: Int
    weight: Float
    height: Float
    notes: String
    recordedAt: String
}